# Use an official Golang runtime as a parent image
FROM golang:1.17-alpine

# Set the working directory inside the container
WORKDIR /app

# Copy the worker source code to the container
COPY mr/mrworker.go .

# Command to run the worker (assuming wc.so is passed as an argument)
CMD ["go", "run", "mrworker.go", "wc.so"]
